title = "Tippecanoe County 4-H Fair"
theme = "universal"
languageCode = "en-us"
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  