############################
## Deployment - Production
############################

order = [".jpg$", ".gif$"]

[[targets]]
# An arbitrary name for this target.
name = "tippe4hfair_site_PRODUCTION"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://www.tippe4hfair.org/?region=us-east-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "EKWLJ9M2DDVBG"

[[matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true