on:
  push:
    tags:
      - preview-*

jobs:
    build:
      runs-on: ubuntu-latest
      environment: preview

      steps:
        - name: Check out main
          uses: actions/checkout@v3
          with:
            submodules: 'recursive'
            fetch-depth: 0

        - name: Checkout schedgen repo
          uses: actions/checkout@v3
          with:
            repository: seliger/schedgen
            path: schedgen

        - name: Generate Schedule Data Files
          uses: actions/setup-python@v4 
          with:
            python-version: '3.10'
            cache: 'pip'
          run: |
            pip install -r schedgen/requirements.txt
            python -m schedgen/schedgen
        
        - name: Deploy site
          uses: seliger/hugo-s3-action@master
          
          env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HUGO_ENVIRONMENT: 'preview'
            MINIFY: 'false'
            TZ: America/New_York
