on:
  push:
    tags:
      - preview-*

jobs:
    build:
      runs-on: ubuntu-latest
      environment: preview

      steps:
        - name: Check out main
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            fetch-depth: 0

        - name: Checkout schedgen repo
          uses: actions/checkout@v4
          with:
            repository: tippe4hexhbit/schedgen
            path: schedgen

        - name: Setup Python environment
          uses: actions/setup-python@v5 
          with:
            python-version: '3.10'
            cache: 'pip'
      
        - name: Generate Schedule Data Files
          run: |
            pip install -r schedgen/requirements.txt
            python -m schedgen
          env:
            AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
            AIRTABLE_BASE: ${{ vars.AIRTABLE_BASE }}
            AIRTABLE_TABLE: ${{ vars.AIRTABLE_TABLE }}
            OUTPUT_DIR: ${{ vars.OUTPUT_DIR }}
            PYTHONPATH: ./schedgen
        
        - name: Deploy site
          uses: seliger/hugo-s3-action@master
          
          env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            HUGO_ENVIRONMENT: 'preview'
            MINIFY: 'false'
            TZ: America/New_York

            